const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY = "GET_COUNTRY";
const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES'
const SET_CONTINENT_FILTER = 'SET_CONTINENT_FILTER'

export { GET_COUNTRIES,GET_COUNTRY, SEARCH_COUNTRIES, SET_CONTINENT_FILTER}