const GET_COUNTRIES = "GET_COUNTRIES";
const GET_ACTIVITIES = "GET_ACTIVITIES";
const GET_COUNTRY = "GET_COUNTRY";
const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
const SET_SEARCH_TERM = "SET_SEARCH_TERM";
const SET_CONTINENT_FILTER = "SET_CONTINENT_FILTER";
const SET_ORDER_FILTER = "SET_ORDER_FILTER";
const SET_POPULATION_FILTER = "SET_POPULATION_FILTER";
const SET_ACTIVITY_SELECT = "SET_ACTIVITY_SELECT";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
const COUNTRIES_FILTERED = "COUNTRIES_FILTERED";
const FAILURE = "FAILURE";
const CREATE_ACTIVITY_SUCCESS = "CREATE_ACTIVITY_SUCCESS";

export {
  GET_COUNTRIES,
  GET_ACTIVITIES,
  GET_COUNTRY,
  SEARCH_COUNTRIES,
  SET_CONTINENT_FILTER,
  FAILURE,
  SET_ORDER_FILTER,
  SET_POPULATION_FILTER,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES,
  COUNTRIES_FILTERED,
  SET_ACTIVITY_SELECT,
  CREATE_ACTIVITY_SUCCESS,
  SET_SEARCH_TERM,
};
